version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'myapp'
      MYSQL_USER: 'myapp'
      MYSQL_PASSWORD: 'myapp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  app:
    build: ..
    restart: always
    environment:
      DB_HOST: db
      DB_USER: 'myapp'
      DB_PASSWORD: 'myapp'
      DB_NAME: 'myapp'
    ports:
      - '3000:3000'
    depends_on:
      - db
