version: '3.9'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .${NODE_ENV:-dev}.env
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_DOCKER_PORT}'
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  app:
    depends_on:
        - db
    build: .
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynetwork
    env_file:
      - .${NODE_ENV:-dev}.env
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    command: npm run start:${NODE_ENV:-dev}
    stdin_open: true
    tty: true

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
