version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynetwork
    env_file:
      - .${NODE_ENV}.env
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    command: npm run start:${NODE_ENV:-dev}
    stdin_open: true
    tty: true

networks:
  mynetwork:
    driver: bridge
