version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynetwork
    env_file:
      - .env.${NODE_ENV}
    environment:
      DB_HOST: db
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      # Add any other environment variables specific to this environment here

    command: npm run ${NODE_ENV}

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
